### ISSUE TITLE
How to use multipe DeepBind models with kipoi_veff2 at once? 

### ISSUE THREAD

**Issue by robertzeibich** [kipoi/kipoi-veff2#37]
I noticed that when "DeepSEA/predict" is used, variants are annotated with the calculated score for a list of predefined models. There does not seem to be an option for DeepBind. How can I use multiple DeepBind models (e.g. DeepBind/Homo_sapiens, /TF/D00331.006_SELEX_DBP, DeepBind/Homo_sapiens/TF/D00332.003_SELEX_DLX1, DeepBind/Homo_sapiens, /TF/D00335.003_SELEX_DLX2, etc.) in a similar manner?

**Comment by haimasree** [comment]
Hi Robert, hello again. There are several ways to do this. However, we used Snakemake. You can find an example [here](https://github.com/kipoi/kipoi/blob/master/notebooks/variant_effect_prediction.ipynb) on the section named ```variant effect prediction at scale```

**Comment by haimasree** [comment]
More specifically, the funciton responsible for converting a model group name to list of models is
```
from kipoi import list_models
all_models = list_models().model
group_to_models = {group : sorted(list(all_models[all_models.str.contains(group)])) for group in groups}
return group_to_models
```

**Comment by robertzeibich** [comment]
Thank you very much for the response. I got my model dictionary now, but I still do not understand how to integrate the dictionary into this piece of code:

model_group = model_name.split("/")[0]
model_group_config_dict = (
variant_centered.VARIANT_CENTERED_MODEL_GROUP_CONFIGS.get(
        model_group, {}
    )
)

model_config = variant_centered.get_model_config(model_name, **model_group_config_dict)
variant_centered.score_variants(
    model_config=model_config,
    vcf_file=in_vcf,
    fasta_file=fasta,
    output_file=out_vcf,
)

**Comment by haimasree** [comment]
A simple for loop will suffice if you strictly want to stay in python. 

```
from kipoi import list_models
from kipoi_veff2 import scores, variant_centered

group = "DeepBind"
all_models = list_models().model
deepbind_models = sorted(list(all_models[all_models.str.contains(group)]))

# vcf_file = "abc.vcf"
# fasta_file = "abc.fa"

for model_name in deepbind_models:
    output_file = f"out.{model_name}.tsv"
    model_group = model_name.split("/")[0]
    model_group_config_dict = (
        variant_centered.VARIANT_CENTERED_MODEL_GROUP_CONFIGS.get(
            model_group, {}
        )
    )

    model_config = variant_centered.get_model_config(model_name, **model_group_config_dict)

    variant_centered.score_variants(
        model_config=model_config,
        vcf_file=vcf_file,
        fasta_file=fasta_file,
        output_file=output_file,
        scoring_functions=[
                {"name": "diff", "func": scores.diff},
                {"name": "logit", "func": scores.logit},
            ]
    )
```

However, as you can probably understand, it will run 927 models in sequence - so depending on your vcf and fasta file it will take a while. Instead if you already know Snakemake and/or would like to try you can see the `variant effect prediction at scale` of this [notebook](https://github.com/kipoi/kipoi/blob/master/notebooks/variant_effect_prediction.ipynb). If this seems too complicated and/or you have only one vcf/fasta pair you can modify [this](https://github.com/kipoi/kipoi-veff2/blob/main/examples/Snakefile) to fit your purpose. It uses the cli from kipoi_veff2 which under the hood uses the python classes. If you would like to retain one output  file per model remove ```rule merge``` and modify ```rule all``` accordingly. Hope this helps.

**Comment by robertzeibich** [comment]
Thank you. This is helpful. Valuable information.

I used a batch job. I receive the following slurm output: WARNING: len(obj.ALT) > 1. Should this concern me? I am not using the most up to date kipoi version (kipoi=0.6.35). Is this why this warning is thrown?  However, in the tsv files a mode score difference was written for each model and SNV. Looks fine to me, but I just wanted to make sure that the script is doing what it is supposed to do. The length of ALT should be 1. Is ALT not be used for calculation? I also wanted to look at the example you provided. When I tried to open the vcf file, I recognized that this seems not to be a proper vcf file because one should be open and read a vcf file without any difficulties. Can you update the vcf file or tell me how I can look at its content?

**Comment by robertzeibich** [comment]
I guess I am good because I compared the score values of kipoi-veff2 with kipoi-veff, they are the same, but nonetheless this error is still confusing. Could you tell me in which python file I can find the line len(obj.ALT) > 1? I would like to look at it.  I also figured out that the test.vcf file is a compressed vcf file (bcf file).

**Comment by haimasree** [comment]
This warning is coming from [here](https://github.com/kipoi/kipoiseq/blob/4cac698f57f276b87b79ce36a6e544ec4188dd5d/kipoiseq/dataclasses.py#L98). kipoiseq which is used by kipoi-veff2, allows working with ony a single nucleotide variation at a time - so if there are multiple alternative alleles for a variant they should each become a row in the input vcf file. Check the first point under preparation section in [the README](https://github.com/kipoi/kipoi-veff2#running-multiple-models-andor-vcffasta-pairs).

**Comment by robertzeibich** [comment]
You were totally right:
chr1    2316305 chr1_2316305_G_C;chr1_2316305_G_A       G       C,A     58      .
Thx for pointing that out.

**Comment by haimasree** [comment]
Great. I am closing the issue. feel free to open another if you need more help.
