### ISSUE TITLE
Appropriate FASTA file to use in kipoi-veff2: hg38.fa or Hg19?

### ISSUE THREAD

**Issue by sukritikumar4** [kipoi/kipoi-veff2#41]
Hello again,

I was wondering if I should use the Hg19 FASTA file for getting variant scores since some models such as DeepSEA and DeepBind use Hg19/Grch37? I was a bit confused about this since the test_dataloader.py files uses hg38 instead. 

Thank you in advance

**Comment by haimasree** [comment]
Hello! Sorry about the reply. As long as you are following the suggestions listed [here](https://github.com/kipoi/kipoi-veff2#running-multiple-models-andor-vcffasta-pairs) you should be fine. Let me know if you found any issue.

**Comment by haimasree** [comment]
Is it okay if I close the issue if your query has been resolved?

**Comment by sukritikumar4** [comment]
Yes thank you.
